name: Docker Build and Push (multi-Dockerfile)

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dockerfile:
          - Dockerfile
          - Dockerfile.mini
        include:
          - dockerfile: Dockerfile
            tag: latest
          - dockerfile: Dockerfile.mini
            tag: mini

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Scan image for vulnerabilities
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: sh0rch/m365proxy:${{ matrix.tag }}
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH

      - name: Push image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./${{ matrix.dockerfile }}
          push: true
          tags: |
            sh0rch/m365proxy:${{ matrix.tag }}
          sbom: true
          provenance: true

      - name: Push image to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./${{ matrix.dockerfile }}
          push: true
          tags: |
            ghcr.io/sh0rch/m365proxy:${{ matrix.tag }}
          sbom: true
          provenance: true

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.3.0

      - name: Sign image with cosign (DockerHub)
        run: |
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY sh0rch/m365proxy:${{ matrix.tag }}
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

      - name: Sign image with cosign (GHCR)
        run: |
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY ghcr.io/sh0rch/m365proxy:${{ matrix.tag }}
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

      - name: Verify image signature (DockerHub)
        run: |
          cosign verify --key env://COSIGN_PUBLIC_KEY sh0rch/m365proxy:${{ matrix.tag }}
        env:
          COSIGN_PUBLIC_KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}

      - name: Verify image signature (GHCR)
        run: |
          cosign verify --key env://COSIGN_PUBLIC_KEY ghcr.io/sh0rch/m365proxy:${{ matrix.tag }}
        env:
          COSIGN_PUBLIC_KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}

