name: Docker Build and Push (multi-Dockerfile)

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dockerfile:
          - Dockerfile
          - Dockerfile.mini
        include:
          - dockerfile: Dockerfile
            tag: latest
          - dockerfile: Dockerfile.mini
            tag: mini

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./${{ matrix.dockerfile }}
          push: false
          tags: sh0rch/m365proxy:${{ matrix.tag }}

      - name: Scan image for vulnerabilities
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: sh0rch/m365proxy:${{ matrix.tag }}
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH

      - name: Push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./${{ matrix.dockerfile }}
          push: true
          tags: |
            sh0rch/m365proxy:${{ matrix.tag }}
            ghcr.io/sh0rch/m365proxy:${{ matrix.tag }}
